repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint {{cookiecutter.script_name}} tests
        language: system
        types:
          - python
      - id: black
        name: black
        entry: poetry run black {{cookiecutter.script_name}} tests
        language: system
        types:
          - python
      - id: flake8
        name: flake8
        entry: poetry run flake8 {{cookiecutter.script_name}} tests
        language: system
        types:
          - python
      - id: isort
        name: isort
        entry: poetry run isort {{cookiecutter.script_name}} tests
        language: system
        types:
          - python
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types:
          - python
        exclude: tests/*
