repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint odd tests
        language: system
        types:
          - python
      - id: black
        name: black
        entry: poetry run black odd tests
        language: system
        types:
          - python
      - id: flake8
        name: flake8
        entry: poetry run flake8 odd tests
        language: system
        types:
          - python
      - id: isort
        name: isort
        entry: poetry run isort odd tests
        language: system
        types:
          - python
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types:
          - python
        exclude: tests/*
